### ISSUE TITLE
VAE-GAN training

### ISSUE THREAD

**Issue by stratomaster31** [pclucas14/lidar_generation#1]
Congratulations for your work!. I've been working on LiDAR restoration for a while, but my results are not very good, since I'm using an unpaired dataset (I have original point clouds and different corrupted point clouds)... I have two simple questions... for training the condiitonal generator, does this model need both versions of the same point cloud (original and corrupted)? and secondly, is the VAE trained together with the GAN, or does it needs pretrained weights for the GAN? Thank you very much for sharing your achievments, :D

**Comment by pclucas14** [comment]
Hi @stratomaster31, 

Both GANs and VAEs are trained independently. As for the process of removing corruptions from LiDARs, all I did was to train the VAE (from scratch) using *clean and preprocessed* lidars. 

It turns out that feeding corrupted LiDARs to this VAE, and reconstructing them removes the corruption by itself! No need for explicit pairing during training, or even to train on corrupted data.

Best, 
Lucas
