### ISSUE TITLE
Data Prepratation Code from Raw point cloud

### ISSUE THREAD

**Issue by prashkmr** [pclucas14/lidar_generation#3]
Hi,

Thanks for the available code and the results for this paper are really unbelievable.
I have one issue during daty loading and the generation process.
The original KITTI data is present in Binary form, at on the KITTI website.
However, the code uses data in the form of npz files. 
Can you specify the way the KITTI data is converted to this format and are there any samples available because I cannot find any dataset on the GitHub repository?

Also can you help tell that for function 
def preprocess(dataset):

in utils.py ehat is the shape of the dataset ie what does it actually contain.
does it contain only 1 point cloud[num_points*3] or multiple point clouds [num_of_pc*num_points*3]

I suppose there is some utility to convert the lidar KITTI data to the npz format that is taken as input in the code.

Please help in this regard.

Thanks,
Prashant

**Comment by pclucas14** [comment]
Hi Prashant!

Thanks for your interest in the paper. You are right it seems the point cloud conversion code is not in the repository. What I did when working on this project was to create a `.npz` file of the preprocessed point clouds to avoid doing the preprocessing multiple times. I'll have a look and try to find the preprocessing code (I'm not sure I still have the `.npz` files)

Best, 
Lucas

**Comment by pclucas14** [comment]
Hi, I added the validation lidar data (It's the only file that was under the github file limit). I'll try to figure out a way to upload the rest in the following days. 

-Lucas

**Comment by pclucas14** [comment]
I added a link to download both training and validation (preprocessed) data in the `kitti_utils/README.MD` file. Feel free to reopen this issue if it's not working.

**Comment by prashkmr** [comment]
A sincere request to you to upload the preprocessing code. It will be helpful when I require to use your work for different point clouds that are indoors. I am currently stuck at converting the new data to the required npz format.
If you could even explain how you did that, that could be also great.

I see that the shape of the data lidar_val.npz is (154, 60, 512, 4)--> Is this the transformation you discuss in Section IV. PROPOSED APPROACH FOR LIDAR GENERATION where H*W*4= 60*512*4 and 154 is the batch size or is it any different.
(60*512*4) is common to all sets(train, test etc). But I suppose 512*4 is able to represent 1 point cloud. Not able to comprehend what 60 is and then the other dimension 154(it would probably be the batch size I guess).

It's a little confusing here for me. I am totally limited to KITTI data currently.

Eagerly awaiting your response.

Thanks,
Prashant

**Comment by pclucas14** [comment]
OK I see. When you download a point cloud from the KITTI dataset, it is a numpy array `arr.shape = (N,4)`, where the four channels are (x,y,z) and r, the reflectance value (which I do not use). The preprocessing I do essentially breaks down the N points into 60 "circles" containing 512 points each. To have a better intuition of what I mean by circles, take a look at Fig. 2 in the paper. In said figure, there are ~12 circles (H), each with a unique color. The 512 (W) here would represent the amount of points each circle has. Note that in this figure there are much fewer points than in a real scan (I removed a bunch of points to make it easier to understand).

In order to understand how to break down the N points into H circles, let's first assume the points are 2D (i.e. that we only have (x,y), no z).  Second, it's important you understand the original ordering in which the Kitti lidars are presented. Going back to figure 2 in the paper, let's say the first point (`arr[0]`) is where the purple and white axes intersect. Following the direction given by the white axis, the first W points are along the dark blue circle. Then, points W to 2W will be the points on the second darkest blue circle, and so on. Therefore, all you need to do in order to obtain this 2D grid of H circles (rows) by W points (columns) is to iterate over the points and detect when you traverse the purple axis. When you do, it means you are starting a new circle. 

You might have do to a different preprocessing if your input is ordered differently, but in my experience LiDAR data usually has this sort of concentric circle ordering. 

The last preprocessing step is to make sure that every circle has the same number of points. If you want your circles to have 512 points, you can cut your circle into 512 slices (just like you would cut a pizza: each slide would have an angle of size 360 degree / 512). Then, you simply average all the points in every slice to get exactly 512 points per circle. 


The code looked something like this: 
```
# read the raw kitti file
raw_lidar = np.fromfile(path, dtype=np.float32).reshape((-1, 4))

processed_lidar, _ = process_velo(raw_lidar, POINTS_PER_LAYER)
```

You can find the code for process_velo in the `kitti_data` folder on this repository


Best, 
Lucas

**Comment by prashkmr** [comment]
Thanks a lot, Lucas, this seems to kill most of my doubts, I had a hunch of this process from the paper, but this explanation makes it a lot clearer.
Will seek your help if any other challenge arises.

Again, thanks for the quick resolution.
-Prashant

**Comment by prashkmr** [comment]
Hi Lucas,

Had one more doubt that Wanted to clarify. The parse_velo.p file inside the kitti_data folder converts a lidar file into [60,512,4]. 
However, I am using my separate files as a point cloud which has fewer points(around 15000 per point cloud) compared to the KITTI data set.

I am printing the length of the line at line no 95 ( len(lines) != 60 : raise Exception('invalid nb un of lines'), I am also printing the  raw_lidar and the processed lidar in the main function
if __name__ == '__main__':
   ..
   ..
   print((raw_lidar))
    print(raw_lidar.shape)
    processed_lidar, _ = process_velo(raw_lidar, 512)
    print(processed_lidar) 


With them, I get len(lines) is not 60, and the code throws out the error always.


`[[-17.08   2.05   3.08   0.  ]
 [-16.26   1.62   2.92   0.  ]
 [-15.52   1.23   2.78   0.  ]
 ...
 [ -3.72  -2.2   -2.49   0.  ]
 [ -3.68  -2.28  -2.49   0.  ]
 [ -3.63  -2.35  -2.49   0.  ]]
(17441, 4)
46
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-116-039ec43bde63> in <module>
      6     print((raw_lidar))
      7     print(raw_lidar.shape)
----> 8     processed_lidar, _ = process_velo(raw_lidar, 512)
      9     print(processed_lidar) #(60, 512, 4)
     10 

<ipython-input-113-1dbf61130945> in process_velo(velo, points_per_layer, stop)
     95     lines = lines[2:-1]
     96     print(len(lines))
---> 97     if len(lines) != 60 : raise Exception('invalid nb un of lines')
     98     out_tensor = np.zeros((60, points_per_layer, 4))
     99     if stop:

Exception: invalid nb un of lines

`


I guess because my point cloud does not have that number of points(compared to KITTI), the elevation angle is not so much and the vertical bins(60 in number),  do not get enough number of points and thus the number of vertical bins falls less than 60 throwing the error.
Is there any way I can change the per bin size such that the number of bins (60) falls within the range in which my data has the elevation angle?

Or is there any way in which I can get this code working with the point clouds with a lesser number of points.
I am attaching the point cloud files I am using in the following link: [here](https://bit.ly/2BWR1ZM)

This is causing to be a bottleneck for me. 
Eagerly awaiting for your help.

Thanks,
Prashant

**Comment by pclucas14** [comment]
Hi,

you will need to write custom processing code if your data is not from KITTI. if you end up with a point cloud of different dimensions, you will also need to modify the model architecture. 

-Lucas

**Comment by Kartik17** [comment]
@pclucas14 While converting from raw point cloud to a spherical image didn't you encountered the issue of two points sharing a common grid on the spherical image. If possible can you share how you achieved a completely bijective mapping between lidar raw pts and spherical image? Thanks.

**Comment by pclucas14** [comment]
Yes, If I recall correctly I took the average of all points falling in the same grid slot. As you have guessed, the mapping is not exactly bijective. You can however make the grid more refined to get a fully bijective mapping.

**Comment by Kartik17** [comment]
Thanks for the information. Also was there a particular reason why you trained the model on 40x256 points as a frame in the KITTI dataset has approx. 100,000 points which are can be represented in higher resolution along Width such as 40x1024 or 40x2048. Was there an issue of GAN not converging to learn the distribution of data?

**Comment by pclucas14** [comment]
I had very little compute at the time, and this seemed like a good compromise between efficiency and precision.
