### ISSUE TITLE
When args '--autoencoder',   is set to 1 iaf argument missing error

### ISSUE THREAD

**Issue by prashkmr** [pclucas14/lidar_generation#4]
Hi Lucas,

For the file vae_2d.py
When I am trying to use the KL divergence loss with the autoencoder by setting the 
args '--autoencoder',  to 0 it gives the following error.
Seems some argument is missing in the command line parameters.
Can you help out here?

File "vae_2d.py", line 50, in <module>
    model = VAE(args).cuda()
  File "/home/prashant/P/ATM/Code/lidar_generation/lidar_generation/models.py", line 104, in __init__
    if not args.autoencoder and args.iaf:
AttributeError: 'Namespace' object has no attribute 'iaf'

Thanks,
Prashant

**Comment by pclucas14** [comment]
Can you give me the command you are running?

**Comment by prashkmr** [comment]
I ran this command for using the KL loss 
python vae_2d.py --no_polar=1 --autoencoder=0
python vae_2d.py --autoencoder=0

-Prashant

**Comment by pclucas14** [comment]
Ok pull the new code and try now. (I used to have setup for [IAF](https://arxiv.org/abs/1606.04934), but I removed it because it was not giving significant gains. It seemed I had forgot it at one place. Should be ok now

**Comment by prashkmr** [comment]
It seems to be giving some output now. Let me check. By the way, one thing that has been puzzling me from a long time is the preprocess function in utils.py
I have not been able to decode it fully. It is doing some filtering along  the 3 coordinates based on some max and min across axes and that is ok.

When I give it a tensor of the shape of (154, 60, 512, 4) it spits out a preprocessed output of 
(152, 2, 40, 256).
I am puzzled at this transformation. Could you please shed some light here?

-Prashant

**Comment by pclucas14** [comment]
The input is first normalized per channel (which is why you have the min / maxes). Then, we make sure the whole H x W grid has valid values. What sometimes happen is that when cutting the 360 deg. space into slices, some slices have no points that fall into them. So I use neighbouring slices to estimate what would be a good value for the missing data.

As for the  (154, 60, 512, 4) to (152, 2, 40, 256), I am simply 1) transposing the axes from BHWC to BCHW and then 2) converting to cylindrical representation. You can find more info here in this [issue](https://github.com/pclucas14/lidar_generation/issues/2#issuecomment-538568251)
